- name: Installation Services
  yum:
    name:
    - libselinux-python
    - libsemanage-python
    - mariadb-server
    - MySQL-python
    - php-mysql
    state: installed
  tags: install
- name: Start firewalld
  service: name=firewalld state=started enabled=yes
  tags: start firewalld
- name: Insert firewalld rule for mysql
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
  tags: enable mysql port
- name: Restart firewalld
  service: name=firewalld state=reloaded enabled=yes
  tags: restarted firewalld
- name: Copy Mysql configuration file
  copy: src=files/my.cnf dest=/etc/my.cnf
  tags: mysql conf copy
- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes
  tags: start mariadb
- name: Create Application Database
  mysql_db: name={{ dbname }} state=present
  tags: create database
- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ dbpassword }} priv=*.*:ALL host='192.168.20.126' state=present
  tags: create user
- name: Move db-load-script to db host
  copy:
    src: /var/lib/jenkins/workspace/bjit_project_1.2/expdb.sql
    dest: /tmp/expdb.sql
  tags: copy sql
- name: Load Inventory Data
  shell: mysql -f < /tmp/expdb.sql/expdb.sql
  tags: run sql
